### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by tiansh** [neverweep/Weibo-Larger-Pics#2]
## 关于样式

`#wlp_img_drag` 可以给加一个 transition 让滚动效果平滑一些
`#wlp_img_wrap` 的 z-index 建议加到 10000 以上，不然左下角的“微音乐”会浮在弹层上面。
`#wlp_cp` 的宽度可以调整到 450 并指定 z-index 避免被视频盖住（还可以考虑在鼠标不在上面的时候给个 opacity ）

```css
#wlp_img_drag { transition: all 0.15s ease; }
#wlp_img_wrap { z-index: 10001; }
#wlp_cp {  width: 450px; z-index: 1; left: calc(50% - 255px); }
```

## 关于快捷键

快捷键 <kbd>F </kbd> 在微博里是“转发”，使用 <kbd>J</kbd>/<kbd>K</kbd> 选中某条微博后，按 <kbd>F</kbd> 可以打开转发的窗口，所以建议考虑换一个。

使用键盘弹出新页面的功能，因为不是鼠标点击操作，会被浏览器的阻止弹框功能阻拦掉。可以考虑检查 `GM_openInTab` 或 `chrome.tabs.create` 是否可用，利用这些接口弹出新页面。

切换到原始比例的功能是否考虑增加一个快捷键？
